# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66116a7e806b1b7e62ce55c5e327ac02e5a37738e2b1cdcdd33e03f607ce512517cf68700ef1ffd861fce39e809f5977d1b6fb9a70796d691beafbd1e1451b75

test:
  secret_key_base: 86b80402659db4c515a30a4e33d31369b610eaa767508843461cb55bcdcf2f477a335c0300e0ced693e47fe4a0613f925eb4e20827b0446040f600941fabedf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
